# builds the kprobes example kernel modules;
# then to use one (as root):  insmod <module_name.ko>

obj-m += kprobe_example.o
obj-m += kretprobe_example.o

KERNELDIR ?= /root/linux/
PWD := $(shell pwd)

modules:
	$(MAKE) -C $(KERNELDIR) M=$(PWD) modules EXTRA_CFLAGS="-g -DDEBUG"

.PHONY: modules

